### ISSUE TITLE
checkout.com payment gateway is not working with onestepcheckout

### ISSUE THREAD

**Issue by BhavikaEbusinessguru** [checkout/checkout-magento-plugin#110]
I am using “Mage One Step Checkout” (http://wiki.magecheckout.com/one-step-checkout/user-guide.html) for my site. Here we have installed, below mentioned extension:
Extension Url : https://github.com/checkout/checkout-magento-plugin.

After installation, we found issues for processing payment with checkout.com using one-step-checkout. Once process with the payment (Checkout.com) Non PCI, it is reloading the same checkout page having error showing as below screen:

![checkout_payment_error](https://user-images.githubusercontent.com/39213598/39955895-79f88358-55f4-11e8-8227-7b629eac8a3c.png)

Also, checked the same payment gateway with default Magento (Magento ver. 1.9.2.4) and its working fine.

I have checked with code as JS and xml layout is not compatible with extension code. Code is using onepage checkout and their layout with class and IDs. So same is not working.

Let me know if can able to provide checkout.com payment gateway code or extension which is compatible with Mage One Step Checkout as extension and support are no longer available.

**Comment by ioan-ghisoi-cko** [comment]
The plugin needs to be customised for the specific One Step Checkout plugin.

Based on our conversation the issue was related to some missing fields compared to the default mode hence the functionality of the default theme.

The issue will be closed since the issue was resolved in the email thread

> The plugin does not offer defualt support for One Step Checkout, but we are happy to assit you in adapting it to your prefered One Step Checkout choice.
