### ISSUE TITLE
Visitor/customer should not be able to move to next step if credit card details are not valid

### ISSUE THREAD

**Issue by daniel-ifrim** [checkout/checkout-magento-plugin#116]
Using Magento 1.9.3.9
Payment method: Checkout.com Credit Card (FramesJs solution)

On Payment Information step a customer/visitor can fill "0" in card number field. Also can fill no data in the credit card form an is still be able to click Continue button. The user should not be allowed to move on.

Also, in last step Place Order button will do nothing in this case because the validation fails silently.
Also please consider that the iframe/Frame JS object may load after Continue button's `onclick="payment.save()"`.

There are no JS errors in browser.

**Comment by avish-bisbeehurry-cko** [comment]
Hi @daniel-ifrim,

Thank you for your inputs.

We will soon release a new version with a fix for this issue.

**Comment by avish-bisbeehurry-cko** [comment]
Hi @daniel-ifrim,

Issue fixed. Closing the issue. 

Please download the latest plugin release from [here](https://github.com/checkout/checkout-magento-plugin/releases)
