### ISSUE TITLE
It is not working in onestep checkout

### ISSUE THREAD

**Issue by anowarsadata** [checkout/checkout-magento-plugin#144]

**Comment by anowarsadata** [comment]
FME QuickCheckout not support this it not working

**Comment by anowarsadata** [comment]
checkout.com payment method is not support FME QuickCheckout v 3.1.1 extension. please check and reply soon.

**Comment by avish-bisbeehurry-cko** [comment]
@anowarsadata 

Can you please try using the branch upa_osc below. 
https://github.com/checkout/checkout-magento-plugin/tree/upa_osc

**Comment by avish-bisbeehurry-cko** [comment]
Closing this issue, please re-open if needed
