### ISSUE TITLE
Admin quote change!

### ISSUE THREAD

**Issue by hwebb** [checkout/checkout-magento-plugin#156]
Please change your Checkoutcom_Ckopayment_Model_CheckoutcomUtils::getQuote() from `Mage::getModel('sales/quote')->load($quoteId);` to the proper `Mage::getSingleton('adminhtml/session_quote')->getQuote();`
Loading a quote from the database is crazy as all the information recently added are in the session, that's the reason why you got the code like `if (empty($billStreet1) && empty($shipStreet1))` because nothing is coming out of that newly fetched quote.
It has been 3 month that I've gave a list of bugs in your code, so far you haven't fixed a single!

**Comment by avish-bisbeehurry-cko** [comment]
@hwebb Thank you for your suggestion. Can you confirm which version of the plugin are you on? We release version 3.0.4 recently with major improvements and bug fixes. Did you try the new version or still using the older version? Can you list the issues you are having with the new version?

**Comment by hwebb** [comment]
I don't think you read what I wrote, can you read and take a look before asking this question?

**Comment by avish-bisbeehurry-cko** [comment]
@hwebb I did read what you wrote and I also said thank you. We are looking into that issue related to the getQuote function. My questions were mainly related to the list of bugs that you said we haven't fixed. If you are not using the the new release, I would strongly advise that you update.
